development:
  adapter: mysql
  database: market_development
  username: sixarm
  password: pswnvvhsmfva
  host: localhost

test:
  adapter: mysql
  database: market_test
  username: sixarm
  password: pswnvvhsmfva
  host: localhost

production:
  adapter: mysql
  database: market
  username: sixarm
  password: pswnvvhsmfva
  host: localhost


